spring.application.name=loggingdemo

logging.level.root=INFO
logging.level.com.example.loggingdemo.controller=DEBUG
logging.level.com.example.loggingdemo.service=TRACE

management.endpoints.web.exposure.include=health,info,metrics

info.app.name=Logging Demo
info.app.version=1.0
info.app.owner=Vishakha
